let header = document.querySelector('.header');
let nav = document.querySelector('.nav');
let ul = document.querySelector('.ul ');
let container = document.querySelector('.container');
let button = document.querySelector('.button');
let content = document.querySelector('.img23');
let box1 = document.querySelector('.box1');
let box2 = document.querySelector('.box2');
let box3 = document.querySelector('.box3');
let section = document.querySelector('.section');
let container1 = document.querySelector('.container1');
let h6 = document.querySelector('.box1 h6');
let h5 = document.querySelector('.box2 h6');
let h4 = document.querySelector('.box3 h6');
let btn1 = document.querySelector('.btn1');
let btn2 = document.querySelector('.btn2');
let btn3 = document.querySelector('.btn3');
button.style.width = '256px';
button.style.height = '36px';
button.style.borderRadius = '12px';
button.style.fontWeight = '400';
button.style.fontSize =  '14.75px';
button.style.lineHeight = '24px';
button.style.color = 'white';
button.style.backgroundColor = ' #FC004A';
button.style.border = 'none';
header.style.width = '1024px';
nav.style.display = 'flex';
nav.style.justifyContent = 'space-between';
nav.style.alignItems = 'center';
nav.style.height = '71px';
ul.style.display = 'flex';
ul.style.gap = '10px';
ul.style.alignItems = 'center';
container.style.padding = '0 25px';
container.style.margin = '0 auto';
container1.style.padding = '0 25px';
container1.style.margin = '0 auto';
ul.style.listStyle = 'none';
content.style.width = '996px';
content.style.height = '300px';
content.style.margin = ' 63px 0 0 0';
box1.style.width = '235px';
box1.style.height = '391px';
box1.style.display = 'flex';
h6.style.fontWeight = '700';
h6.style.fontSize = '17.66px';
h6.style.lineHeight = '28px';
h5.style.fontWeight = '700';
h5.style.fontSize = '17.66px';
h5.style.lineHeight = '28px';
h4.style.fontWeight = '700';
h4.style.fontSize = '17.66px';
h4.style.lineHeight = '28px';
box1.style.alignItems = 'left';
box1.style.flexDirection = 'column';
box2.style.width = '235px';
box2.style.height = '391px';
box2.style.display = 'flex';
box2.style.alignItems = 'left';
box2.style.flexDirection = 'column';
box3.style.width = '235px';
box3.style.height = '391px'
box3.style.display = 'flex';
box3.style.alignItems = 'left';
box3.style.flexDirection = 'column';
section.style.width = '1024px';
section.style.display = 'flex';
section.style.justifyContent = 'space-evenly';
section.style.padding = '30px 0'
btn1.style.width = '40px';
btn1.style.height = '40px';
btn1.style.color = 'white';
btn1.style.border = 'none';
btn1.style.backgroundColor = ' #FC004A';

btn2.style.width = '40px';
btn2.style.height = '40px';
btn2.style.color = 'white';
btn2.style.border = 'none';
btn2.style.backgroundColor = ' #FC004A';

btn3.style.width = '40px';
btn3.style.height = '40px';
btn3.style.color = 'white';
btn3.style.border = 'none';
btn3.style.backgroundColor = ' #FC004A';



document.querySelector('.btn1').addEventListener('click', () => {
    let prompt1 = prompt("Qiyriq set nechta zakaz qilmoqchisiz?");
    let prompt2 = confirm("Zakaz narxi :" + prompt1*45000 + "\n \n Zakaz qilasizmi?");
    let prompt3 = confirm("Zakaz qabul qilindi");
})
document.querySelector('.btn2').addEventListener('click', () => {
    let prompt1 = prompt(" Snek set nechta zakaz qilmoqchisiz?");
    let prompt2 = confirm("Zakaz narxi :" + prompt1*79000 + "\n \n Zakaz qilasizmi?");
    let prompt3 = confirm("Zakaz qabul qilindi");
})
document.querySelector('.btn3').addEventListener('click', () => {
    let prompt1 = prompt("Klassik set nechta zakaz qilmoqchisiz?");
    let prompt2 = confirm("Zakaz narxi :" + prompt1*34000 + "\n \n Zakaz qilasizmi?");
    let prompt3 = confirm("Zakaz qabul qilindi");
})